### ISSUE TITLE
pebble.ConnectionError occurs after logging relation joined

### ISSUE THREAD

**Issue by gatici** [canonical/loki-k8s-operator#361] opened 2024-03-08 13:56 UTC
### Bug Description

In loki_push_api.py pebble.ConnectionError  needs to be handled properly.

### To Reproduce

1. juju deploy sdcore-nms-k8s  --channel 1.3/edge
2. juju deploy  grafana-agent-k8s  --channel      latest/stable
3.  juju integrate sdcore-nms-k8s  grafana-agent-k8s
4. Check the nms pod logs: kubectl logs -f nms-0 -n model-name 

### Environment

juju: 3.4.0
microk8s: 1.27

### Relevant log output

```shell
2024-03-08T10:19:04.430Z [container-agent] 2024-03-08 10:19:04 WARNING juju-log logging:9: The relation 'logging' is not ready yet.
2024-03-08T10:19:04.431Z [container-agent] 2024-03-08 10:19:04 WARNING juju-log logging:9: No Loki endpoints available
2024-03-08T10:19:04.681Z [container-agent] 2024-03-08 10:19:04 INFO juju.worker.uniter.operation runhook.go:186 ran "logging-relation-changed" hook (via hook dispatching script: dispatch)
2024-03-08T10:19:05.140Z [container-agent] 2024-03-08 10:19:05 INFO juju.worker.uniter.operation runhook.go:186 ran "sdcore-management-relation-joined" hook (via hook dispatching script: dispatch)
2024-03-08T10:19:05.628Z [container-agent] 2024-03-08 10:19:05 INFO juju.worker.uniter.operation runhook.go:186 ran "sdcore-management-relation-changed" hook (via hook dispatching script: dispatch)
2024-03-08T10:19:05.891Z [container-agent] 2024-03-08 10:19:05 ERROR juju-log logging:9: Uncaught exception while in charm code:
2024-03-08T10:19:05.891Z [container-agent] Traceback (most recent call last):
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/./src/charm.py", line 274, in <module>
2024-03-08T10:19:05.891Z [container-agent]     main(SDCoreNMSOperatorCharm)
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/main.py", line 456, in main
2024-03-08T10:19:05.891Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
2024-03-08T10:19:05.891Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 352, in emit
2024-03-08T10:19:05.891Z [container-agent]     framework._emit(event)
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 865, in _emit
2024-03-08T10:19:05.891Z [container-agent]     self._reemit(event_path)
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 955, in _reemit
2024-03-08T10:19:05.891Z [container-agent]     custom_handler(event)
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/lib/charms/loki_k8s/v1/loki_push_api.py", line 2526, in _update_logging
2024-03-08T10:19:05.891Z [container-agent]     _PebbleLogClient.disable_inactive_endpoints(
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/lib/charms/loki_k8s/v1/loki_push_api.py", line 2450, in disable_inactive_endpoints
2024-03-08T10:19:05.891Z [container-agent]     pebble_layer = container.get_plan().to_dict().get("log-targets", None)
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/model.py", line 2178, in get_plan
2024-03-08T10:19:05.891Z [container-agent]     return self._pebble.get_plan()
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 2105, in get_plan
2024-03-08T10:19:05.891Z [container-agent]     resp = self._request('GET', '/v1/plan', {'format': 'yaml'})
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 1772, in _request
2024-03-08T10:19:05.891Z [container-agent]     response = self._request_raw(method, path, query, headers, data)
2024-03-08T10:19:05.891Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 1821, in _request_raw
2024-03-08T10:19:05.891Z [container-agent]     raise ConnectionError(
2024-03-08T10:19:05.891Z [container-agent] ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/nms/pebble.socket' (container restarted?)
2024-03-08T10:19:06.116Z [container-agent] 2024-03-08 10:19:06 ERROR juju.worker.uniter.operation runhook.go:180 hook "logging-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
2024-03-08T10:19:06.117Z [container-agent] 2024-03-08 10:19:06 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:11.134Z [container-agent] 2024-03-08 10:19:11 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:11.335Z [container-agent] 2024-03-08 10:19:11 ERROR juju-log logging:9: Uncaught exception while in charm code:
2024-03-08T10:19:11.335Z [container-agent] Traceback (most recent call last):
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/./src/charm.py", line 274, in <module>
2024-03-08T10:19:11.335Z [container-agent]     main(SDCoreNMSOperatorCharm)
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/main.py", line 456, in main
2024-03-08T10:19:11.335Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
2024-03-08T10:19:11.335Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 352, in emit
2024-03-08T10:19:11.335Z [container-agent]     framework._emit(event)
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 865, in _emit
2024-03-08T10:19:11.335Z [container-agent]     self._reemit(event_path)
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 955, in _reemit
2024-03-08T10:19:11.335Z [container-agent]     custom_handler(event)
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/lib/charms/loki_k8s/v1/loki_push_api.py", line 2526, in _update_logging
2024-03-08T10:19:11.335Z [container-agent]     _PebbleLogClient.disable_inactive_endpoints(
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/lib/charms/loki_k8s/v1/loki_push_api.py", line 2450, in disable_inactive_endpoints
2024-03-08T10:19:11.335Z [container-agent]     pebble_layer = container.get_plan().to_dict().get("log-targets", None)
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/model.py", line 2178, in get_plan
2024-03-08T10:19:11.335Z [container-agent]     return self._pebble.get_plan()
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 2105, in get_plan
2024-03-08T10:19:11.335Z [container-agent]     resp = self._request('GET', '/v1/plan', {'format': 'yaml'})
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 1772, in _request
2024-03-08T10:19:11.335Z [container-agent]     response = self._request_raw(method, path, query, headers, data)
2024-03-08T10:19:11.335Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 1821, in _request_raw
2024-03-08T10:19:11.335Z [container-agent]     raise ConnectionError(
2024-03-08T10:19:11.335Z [container-agent] ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/nms/pebble.socket' (container restarted?)
2024-03-08T10:19:11.559Z [container-agent] 2024-03-08 10:19:11 ERROR juju.worker.uniter.operation runhook.go:180 hook "logging-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
2024-03-08T10:19:11.560Z [container-agent] 2024-03-08 10:19:11 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:12.533Z [container-agent] 2024-03-08 10:19:12 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:21.419Z [container-agent] 2024-03-08 10:19:21 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:21.646Z [container-agent] 2024-03-08 10:19:21 ERROR juju-log logging:9: Uncaught exception while in charm code:
2024-03-08T10:19:21.646Z [container-agent] Traceback (most recent call last):
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/./src/charm.py", line 274, in <module>
2024-03-08T10:19:21.646Z [container-agent]     main(SDCoreNMSOperatorCharm)
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/main.py", line 456, in main
2024-03-08T10:19:21.646Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
2024-03-08T10:19:21.646Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 352, in emit
2024-03-08T10:19:21.646Z [container-agent]     framework._emit(event)
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 865, in _emit
2024-03-08T10:19:21.646Z [container-agent]     self._reemit(event_path)
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 955, in _reemit
2024-03-08T10:19:21.646Z [container-agent]     custom_handler(event)
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/lib/charms/loki_k8s/v1/loki_push_api.py", line 2526, in _update_logging
2024-03-08T10:19:21.646Z [container-agent]     _PebbleLogClient.disable_inactive_endpoints(
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/lib/charms/loki_k8s/v1/loki_push_api.py", line 2450, in disable_inactive_endpoints
2024-03-08T10:19:21.646Z [container-agent]     pebble_layer = container.get_plan().to_dict().get("log-targets", None)
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/model.py", line 2178, in get_plan
2024-03-08T10:19:21.646Z [container-agent]     return self._pebble.get_plan()
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 2105, in get_plan
2024-03-08T10:19:21.646Z [container-agent]     resp = self._request('GET', '/v1/plan', {'format': 'yaml'})
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 1772, in _request
2024-03-08T10:19:21.646Z [container-agent]     response = self._request_raw(method, path, query, headers, data)
2024-03-08T10:19:21.646Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 1821, in _request_raw
2024-03-08T10:19:21.646Z [container-agent]     raise ConnectionError(
2024-03-08T10:19:21.646Z [container-agent] ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/nms/pebble.socket' (container restarted?)
2024-03-08T10:19:21.871Z [container-agent] 2024-03-08 10:19:21 ERROR juju.worker.uniter.operation runhook.go:180 hook "logging-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
2024-03-08T10:19:21.872Z [container-agent] 2024-03-08 10:19:21 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:40.981Z [container-agent] 2024-03-08 10:19:40 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:41.207Z [container-agent] 2024-03-08 10:19:41 ERROR juju-log logging:9: Uncaught exception while in charm code:
2024-03-08T10:19:41.207Z [container-agent] Traceback (most recent call last):
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/./src/charm.py", line 274, in <module>
2024-03-08T10:19:41.207Z [container-agent]     main(SDCoreNMSOperatorCharm)
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/main.py", line 456, in main
2024-03-08T10:19:41.207Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
2024-03-08T10:19:41.207Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 352, in emit
2024-03-08T10:19:41.207Z [container-agent]     framework._emit(event)
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 865, in _emit
2024-03-08T10:19:41.207Z [container-agent]     self._reemit(event_path)
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/framework.py", line 955, in _reemit
2024-03-08T10:19:41.207Z [container-agent]     custom_handler(event)
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/lib/charms/loki_k8s/v1/loki_push_api.py", line 2526, in _update_logging
2024-03-08T10:19:41.207Z [container-agent]     _PebbleLogClient.disable_inactive_endpoints(
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/lib/charms/loki_k8s/v1/loki_push_api.py", line 2450, in disable_inactive_endpoints
2024-03-08T10:19:41.207Z [container-agent]     pebble_layer = container.get_plan().to_dict().get("log-targets", None)
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/model.py", line 2178, in get_plan
2024-03-08T10:19:41.207Z [container-agent]     return self._pebble.get_plan()
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 2105, in get_plan
2024-03-08T10:19:41.207Z [container-agent]     resp = self._request('GET', '/v1/plan', {'format': 'yaml'})
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 1772, in _request
2024-03-08T10:19:41.207Z [container-agent]     response = self._request_raw(method, path, query, headers, data)
2024-03-08T10:19:41.207Z [container-agent]   File "/var/lib/juju/agents/unit-nms-0/charm/venv/ops/pebble.py", line 1821, in _request_raw
2024-03-08T10:19:41.207Z [container-agent]     raise ConnectionError(
2024-03-08T10:19:41.207Z [container-agent] ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/nms/pebble.socket' (container restarted?)
2024-03-08T10:19:41.440Z [container-agent] 2024-03-08 10:19:41 ERROR juju.worker.uniter.operation runhook.go:180 hook "logging-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
2024-03-08T10:19:41.440Z [container-agent] 2024-03-08 10:19:41 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:43.207Z [container-agent] 2024-03-08 10:19:43 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:47.972Z [container-agent] 2024-03-08 10:19:47 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:52.409Z [container-agent] 2024-03-08 10:19:52 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:19:53.587Z [container-agent] 2024-03-08 10:19:53 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
2024-03-08T10:20:18.905Z [container-agent] 2024-03-08 10:20:18 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-joined" hook
```

**Comment by michaeldmitry** [comment] 2024-04-17 11:27
@gatici 
A relation on sdcore-nms (sdcore-management) is missing from the above steps that is blocking subsequent steps

I was not able to reproduce the issue you faced even after following the below steps:
1- juju deploy grafana-agent-k8s --channel latest/stable
2- juju deploy sdcore-nms-k8s --channel 1.3/edge
3- juju integrate sdcore-nms-k8s:sdcore-management sdcore-webui-k8s:sdcore-management
4- juju integrate sdcore-nms-k8s grafana-agent-k8s

no exceptions were fired from the charms' side.
After integrating with cos-lite
1- juju deploy cos-lite --trust 
(revision 11 channel latest/stable)
2- juju integrate grafana-agent-k8s:logging-consumer loki:logging

All logs from sdcore workload container are pushed successfully to Loki.
juju version: 3.4.2
microk8s version: v1.28.7

will close the issue for now and please feel free to reopen if the issue still persists

**Closed by michaeldmitry** 2024-04-17 11:27 UTC
Labels: Type: Bug, Status: Triage
