### ISSUE TITLE
Loki push api: ModelError on relation-departed

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/loki-k8s-operator#102] opened 2022-02-24 15:24 UTC
This happens from time to time on `juju remove-application loki-k8s`; might be a timing issue, if the relation-departed is queued after the databag gets deleted?

```
in _on_relation_departed                                                                                  
    new_config = self._promtail_config                                                                    
  File "/var/lib/juju/agents/unit-loki-tester-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1890,
in _promtail_config                                                                                       
    config = {"clients": self._clients_list()}                                                            
  File "/var/lib/juju/agents/unit-loki-tester-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1904,
in _clients_list                                                                                          
    clients = clients + json.loads(relation.data[relation.app]["endpoints"])                              
  File "/var/lib/juju/agents/unit-loki-tester-0/charm/venv/ops/model.py", line 430, in __getitem__        
    return self._data[key]                                                                                
  File "/var/lib/juju/agents/unit-loki-tester-0/charm/venv/ops/model.py", line 414, in _data              
    data = self._lazy_data = self._load()                                                                 
  File "/var/lib/juju/agents/unit-loki-tester-0/charm/venv/ops/model.py", line 779, in _load              
    return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)                  
  File "/var/lib/juju/agents/unit-loki-tester-0/charm/venv/ops/model.py", line 1588, in relation_get      
    return self._run(*args, return_output=True, use_json=True)                                            
  File "/var/lib/juju/agents/unit-loki-tester-0/charm/venv/ops/model.py", line 1523, in _run              
    raise ModelError(e.stderr)                                                                            
ops.model.ModelError: b'ERROR permission denied\n'                                                        
```

**Comment by sed-i** [comment] 2022-03-22 07:23
Something similar happens on `juju relate`/`relation-changed`:

```
cass/0*  error     idle   10.1.73.149         hook failed: "log-proxy-relation-changed" for loki:logging
```
```
unit-cass-0: 07:21:03.144 ERROR unit.cass/0.juju-log log-proxy:2: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 308, in <module>
    main(CassandraOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/main.py", line 426, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/framework.py", line 276, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/framework.py", line 736, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/framework.py", line 783, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cass-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1637, in _on_relation_changed
    new_config = self._promtail_config
  File "/var/lib/juju/agents/unit-cass-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1874, in _promtail_config
    config = {"clients": self._clients_list()}
  File "/var/lib/juju/agents/unit-cass-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1888, in _clients_list
    clients = clients + json.loads(relation.data[relation.app]["endpoints"])
  File "/var/lib/juju/agents/unit-cass-0/charm/venv/ops/model.py", line 430, in __getitem__
    return self._data[key]
KeyError: 'endpoints'
unit-cass-0: 07:21:03.387 ERROR juju.worker.uniter.operation hook "log-proxy-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by mmanciop** [comment] 2022-04-05 12:49
Likely due to https://github.com/canonical/operator/issues/693

**Comment by sed-i** [comment] 2022-04-29 13:43
Fixed by https://github.com/canonical/loki-k8s-operator/pull/150

**Comment by cbartz** [comment] 2023-11-21 09:16
@sed-i @PietroPasotti We had this issue today using revision `101` (`latest/edge`). 

Logs:
```
unit-loki-0: 09:06:24 DEBUG unit.loki/0.juju-log logging:64: ops 2.7.0 up and running.
unit-loki-0: 09:06:24 DEBUG unit.loki/0.juju-log logging:64: load_ssl_context verify='/var/run/secrets/kubernetes.io/serviceaccount/ca.crt' cert=None trust_env=True http2=False
unit-loki-0: 09:06:24 DEBUG unit.loki/0.juju-log logging:64: load_verify_locations cafile='/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
unit-loki-0: 09:06:24 DEBUG unit.loki/0.juju-log logging:64: This unit's ingress URL: http://private
unit-loki-0: 09:06:24 DEBUG unit.loki/0.juju-log logging:64: This unit's ingress URL: http://private
unit-loki-0: 09:06:24 DEBUG unit.loki/0.juju-log logging:64: This unit's ingress URL: http://private
unit-loki-0: 09:06:24 DEBUG unit.loki/0.juju-log logging:64: Emitting Juju event logging_relation_changed.
unit-loki-0: 09:06:24 DEBUG unit.loki/0.juju-log logging:64: Saved endpoint in unit relation data
unit-loki-0: 09:06:25 DEBUG unit.loki/0.juju-log logging:64: Emitting custom event <LokiPushApiAlertRulesChanged via LokiOperatorCharm/LokiPushApiProvider[logging]/on/loki_push_api_alert_rules_changed[19744]>.
unit-loki-0: 09:06:25 ERROR unit.loki/0.juju-log logging:64: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 2838, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-loki-0/relation-get', '-r', '40', '-', 'remote-9a67374a9a7449338cf89003d93002fa', '--app', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 533, in <module>
    main(LokiOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 342, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 928, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1155, in _on_logging_relation_changed
    self.on.loki_push_api_alert_rules_changed.emit(
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 342, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 928, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 407, in _loki_push_api_alert_rules_changed
    self._regenerate_alert_rules()
  File "./src/charm.py", line 433, in _regenerate_alert_rules
    if self.loki_provider.alerts:
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1321, in alerts
    alert_rules = json.loads(relation.data[relation.app].get("alert_rules", "{}"))
  File "/usr/lib/python3.8/_collections_abc.py", line 660, in get
    return self[key]
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1628, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 732, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 716, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1512, in _load
    return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 2919, in relation_get
    raw_data_content = self._run(*args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 2840, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: ERROR permission denied

unit-loki-0: 09:06:25 ERROR juju.worker.uniter.operation hook "logging-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

```

**Comment by cbartz** [comment] 2023-11-21 10:31
@PietroPasotti Sorry, we have already resolved the issue using `juju resolved` , so its now in `active`. Here is the current status output: https://pastebin.canonical.com/p/mbDRKtvsWm/

We have only one loki unit and the output showed `hook failed: "logging-relation-departed"`

**Comment by PietroPasotti** [comment] 2023-11-21 10:45
interesting, because the logs say the charm was running `logging_relation_changed` when the crash occurred. Maybe it was deferred? @sed-i

**Comment by cbartz** [comment] 2023-11-21 10:49
Beyond that, but this might be unrelated, we currently have an error in update-status:

```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 2838, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-loki-0/network-get', 'metrics-endpoint', '-r', '14', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 533, in <module>
    main(LokiOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 342, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 928, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/prometheus_k8s/v0/prometheus_scrape.py", line 1523, in set_scrape_job_spec
    self._set_unit_ip()
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/prometheus_k8s/v0/prometheus_scrape.py", line 1554, in _set_unit_ip
    unit_ip = str(self._charm.model.get_binding(relation).network.bind_address)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 871, in network
    self._network = self._network_get(self.name, self._relation_id)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 864, in _network_get
    return Network(self._backend.network_get(name, relation_id))
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 3123, in network_get
    network = self._run(*cmd, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 2840, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: ERROR relation 14 not found (not found)

unit-loki-0: 10:43:31 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
```
more here https://pastebin.canonical.com/p/DgbQ7QQdpB/

**Comment by cbartz** [comment] 2023-11-21 11:42
Before the `logging-relation-changed` error happenend, we did a `juju remove-offer prometheus-receive-remote-write --force`

**Comment by PietroPasotti** [comment] 2023-11-21 11:51
that might be it then

**Comment by sed-i** [comment] 2023-11-21 14:27
On one hand, a forceful removal of some charm shouldn't break the charms that are left (currently they are stuck in a hook resolve error loop).
On the other hand, it is probably impractical to sprinkle `except ModelError. And charm code doesn't have insight about the reason.

Any ideas @benhoyt @tonyandrewmeyer @jameinel?

**Comment by lucabello** [comment] 2024-01-11 10:52
Gentle ping on this? Any followup?

@benhoyt @tonyandrewmeyer @jameinel @sed-i

**Comment by benhoyt** [comment] 2024-01-11 22:12
There seem to be a few different issues noted above, and I'm struggling to follow what the problem is exactly. If you force-remove one application (or relation?), other charms start raising errors? Can someone describe the problem accurately?

**Comment by simskij** [comment] 2024-03-12 13:52
This is as old as the charm, and the last relevant comment I can see is that it likely was due to forcefully removing an offer. If this is still a problem, please open a new issue with a contained reproducer.

**Closed by simskij** 2024-03-12 13:52 UTC
Labels: Type: Bug

**Comment by verterok** [comment] 2025-01-30 13:07
Hi, 
I am getting a similar error after using `--force`, had to do a couple of `resolved --no-retry` and once the error was cleared any new relation added or removed causes the hook to fail with `permission denied`

```
unit-loki-0: 13:06:18 ERROR unit.loki/0.juju-log logging:77: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 3022, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-loki-0/relation-get', '-r', '59', '-', 'remote-a182ecc3896547b983eff126b6f9bddd', '--app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./src/charm.py", line 671, in <module>
    main(LokiOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 506, in _emit
    self.framework.reemit()
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 861, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 941, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 547, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1185, in _on_logging_relation_departed
    self.on.loki_push_api_alert_rules_changed.emit(
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 352, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 851, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 941, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 547, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "./src/charm.py", line 524, in _loki_push_api_alert_rules_changed
    self._regenerate_alert_rules()
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 547, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "./src/charm.py", line 550, in _regenerate_alert_rules
    if self.loki_provider.alerts:
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1323, in alerts
    alert_rules = json.loads(relation.data[relation.app].get("alert_rules", "{}"))
  File "/usr/lib/python3.8/_collections_abc.py", line 660, in get
    return self[key]
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1705, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 806, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 790, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1589, in _load
    return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 3095, in relation_get
    raw_data_content = self._run(*args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 3024, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied
```

Is there a way to recover from this?
